### ISSUE TITLE
Consider using UOPZ for testing

### ISSUE THREAD

**Issue by henriquemoody** [nelsonsar/microqueue#1]
I have the same problem with tests when I wrote [Arara\Process](https://github.com/Arara/Process), my first thought was overwrite the native PHP functions by namespace but it usually caused problems since you overwrite a function into a test case file but the same function could be used in other test cases.

After some research I got those alternatives:

**Libraries**
- [MockFunction](https://github.com/tcz/phpunit-mockfunction)
- [PHPBuiltinMock](https://github.com/jadell/PHPBuiltinMock)

**Extensions**
- [APD](http://php.net/manual/en/book.apd.php)
- [Runkit](http://php.net/manual/en/book.runkit.php)
- [UOPZ](https://github.com/krakjoe/uopz)

I end up using UOPZ on [my tests](https://github.com/Arara/Process/blob/master/tests/unit/Arara/Process/Control/SignalTest.php#L34-L39), it's pretty awful sometimes specially if you don't like _reflection stuff_  but I have a fully tested code base.

PS.: Great library I'll probably use it with Arara\Process sometime.

**Comment by nelsonsar** [comment]
Nice, man! Thanks for helping me with this :)

I'll check all of them later and try to choose one. My only concern is mocking what I maybe shouldn't mock, but, I don't think we have much option in cases like these, right?

Again, thanks for this and for your feedback!

**Comment by henriquemoody** [comment]
You're welcome. :smile: 

I don't like the idea too, sometimes you have problems just because you mock and them you don't get the real behavior.

Each approach has a cost.

**Comment by henriquemoody** [comment]
Outdated.

PS.: I'm closing my older issues, please reopen if you think it's relevante.
